### ISSUE TITLE
The future of tokio in audioipc

### ISSUE THREAD

**Issue by Eijebong** [mozilla/audioipc-2#97]
Hey, tried updating tokio in here this weekend, got it to compile but it's not working. When I asked on #media, I was told that audioipc might get off tokio in a soon-ish future. What's the state of that ? Should I bother trying to finish the tokio bump ?

My work is here: https://github.com/Eijebong/audioipc-2/tree/all-i-wanted-this-weekend-was-to-play-minecraft-I-failed

**Comment by kinetiknz** [comment]
Thanks for attempting this!  There's no concrete plan to replace tokio at this stage, although it's a continuing thread of discussion.  I've been meaning to try updating to tokio 0.2 to see what's involved as part of evaluating whether to continue with tokio or move to a solution better suited to AudioIPC's needs.

Since it's important for us to control which threads various code runs on, we've (ab)used tokio's current_thread support for this... I haven't explored tokio 0.2's LocalSet in detail yet to see how it works as a replacement.

When I have time I'll see if I can get ipctest working based on the changes in your branch.  If you make any progress, please let me know.

**Comment by kinetiknz** [comment]
As mentioned [here](https://github.com/mozilla/audioipc-2/issues/110), the current plan is remove our dependency on tokio.

That'll be tracked in [bug 1697845](https://bugzilla.mozilla.org/show_bug.cgi?id=1697845).
